"""iCloud Hide My Email provider and protocol helpers.

This module is intentionally small and local to this project. It mirrors the
request shape used by Apple's iCloud web client for Hide My Email generation,
listing, and reservation, then exposes the same provider interface consumed by
``AuthFlow.run_register``: ``create_mailbox()`` and ``wait_for_otp()``.
"""
from __future__ import annotations

import base64
import email as _email
import email.utils as _email_utils
import html
import imaplib
import json
import logging
import re
import time
import urllib.parse
from dataclasses import dataclass
from datetime import timezone
from email import policy
from email.message import EmailMessage
from email.parser import BytesParser
from typing import Iterable, Optional

import requests

logger = logging.getLogger(__name__)

REQUEST_TIMEOUT_SECONDS = 30
REQUEST_RETRIES = 2
DEFAULT_HME_NOTE = "Generated by gpt-outlook-register"

REGION_CONFIG = {
    "global": {
        "maildomain_host": "p68-maildomainws.icloud.com",
        "web_origin": "https://www.icloud.com",
        "setup_validate_url": "https://setup.icloud.com/setup/ws/1/validate",
        "accept_language": "en-US,en;q=0.7",
        "lang_code": "en-us",
        "suffix": "com",
    },
    "china": {
        "maildomain_host": "p217-maildomainws.icloud.com.cn",
        "web_origin": "https://www.icloud.com.cn",
        "setup_validate_url": "https://setup.icloud.com.cn/setup/ws/1/validate",
        "accept_language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        "lang_code": "zh-cn",
        "suffix": "com.cn",
    },
}

CLIENT_PARAMS = {
    "clientBuildNumber": "2626Build17",
    "clientMasteringNumber": "2626Build17",
    "clientId": "",
    "dsid": "",
}

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"
)
SEC_CH_UA = '"Not;A=Brand";v="8", "Chromium";v="150", "Brave";v="150"'

CODE_KEYWORDS_RE = re.compile(
    r"验证码|校验码|动态码|安全码|认证码|确认码|临时码|一次性|验证|verification|verify|code|otp|passcode|security code|confirmation",
    re.IGNORECASE,
)
DIGIT_CODE_RE = re.compile(r"(?<!\d)\d{4,8}(?!\d)")
ALNUM_CODE_RE = re.compile(
    r"\b(?=[A-Z0-9]{6,10}\b)(?=[A-Z0-9]*[A-Z])(?=[A-Z0-9]*\d)[A-Z0-9]{6,10}\b"
)
EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
TAG_RE = re.compile(r"<[^>]+>")

RECIPIENT_HEADERS = [
    "To",
    "Delivered-To",
    "X-Original-To",
    "Envelope-To",
    "X-Envelope-To",
    "Apparently-To",
    "Original-Recipient",
    "Resent-To",
    "Cc",
    "Bcc",
]


def _truthy(value) -> bool:
    if isinstance(value, bool):
        return value
    return str(value or "").strip().lower() in ("1", "true", "yes", "on")


def normalize_cookie(raw: str) -> str:
    """Accept raw cookie, simple cURL snippets, cookie header, or base64 marker."""
    content = "\n".join(
        line.strip() for line in (raw or "").splitlines()
        if not line.lstrip().startswith("//")
    ).strip()
    if not content:
        return ""

    normalized = (
        content.replace('^"', '"')
        .replace("^'", "'")
        .replace("^\n", "")
        .replace("^\r\n", "")
    )

    encoded = re.search(r"(?m)^HIDEMYEMAIL_COOKIE_BASE64=([A-Za-z0-9+/=]+)\s*$", normalized)
    if encoded:
        return base64.b64decode(encoded.group(1)).decode("utf-8").strip()

    cmd_cookie_arg = re.search(
        r"(?:^|\s)(?:-b|--cookie)\s+\^\"(.+?)\^\"\s+\^?\s*-[A-Za-z]",
        content,
        re.IGNORECASE | re.DOTALL,
    )
    if cmd_cookie_arg:
        return (
            cmd_cookie_arg.group(1)
            .replace('^\\^"', '"')
            .replace('\\"', '"')
            .replace('^"', '"')
            .replace("\r", "")
            .replace("\n", "")
            .strip()
        )

    cookie_arg = re.search(r"(?:^|\s)(?:-b|--cookie)\s+\"([^\"]+)\"", normalized, re.IGNORECASE)
    if cookie_arg:
        return cookie_arg.group(1).strip()

    cookie_header = re.search(r"cookie\s*:\s*([^'\"\r\n]+)", normalized, re.IGNORECASE)
    if cookie_header:
        return cookie_header.group(1).strip()

    return normalized.splitlines()[0].strip()


def detect_maildomain_host(raw: str, region: str) -> str:
    explicit = re.search(r"(?m)^HIDEMYEMAIL_MAILDOMAIN_HOST=([A-Za-z0-9.-]+)\s*$", raw or "")
    if explicit:
        return explicit.group(1).strip()
    shard = re.search(r"https://(p\d+)-[^/\s'\"]+\.icloud\.com(?:\.cn)?", raw or "")
    if shard:
        suffix = REGION_CONFIG[region]["suffix"]
        return f"{shard.group(1)}-maildomainws.icloud.{suffix}"
    return ""


def browser_headers(region: str, cookie: str = "") -> dict:
    cfg = REGION_CONFIG[region]
    return {
        "Connection": "keep-alive",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache",
        "User-Agent": USER_AGENT,
        "Content-Type": "text/plain",
        "Accept": "*/*",
        "Sec-GPC": "1",
        "Origin": cfg["web_origin"],
        "Sec-Fetch-Site": "same-site",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Dest": "empty",
        "Referer": f"{cfg['web_origin']}/",
        "Accept-Language": cfg["accept_language"],
        "sec-ch-ua": SEC_CH_UA,
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"macOS"',
        "Cookie": cookie.strip(),
    }


def maildomain_from_partition(region: str, partition) -> str:
    if partition in (None, ""):
        return ""
    try:
        part = int(partition)
    except (TypeError, ValueError):
        return ""
    suffix = REGION_CONFIG[region]["suffix"]
    return f"p{part}-maildomainws.icloud.{suffix}"


def _json_error(message: str, code: Optional[str] = None) -> dict:
    return {"error": {"code": code, "message": message}}


class ICloudHMEClient:
    def __init__(self, cookie: str, region: str = "global", maildomain_host: str = "", session=None):
        region = (region or "global").strip().lower()
        if region not in REGION_CONFIG:
            raise ValueError(f"unsupported iCloud region: {region}")
        raw_cookie = cookie or ""
        self.region = region
        self.cookie = normalize_cookie(raw_cookie)
        self.maildomain_host = (maildomain_host or detect_maildomain_host(raw_cookie, region) or REGION_CONFIG[region]["maildomain_host"]).strip()
        self.base_url_v1 = f"https://{self.maildomain_host}/v1/hme"
        self.base_url_v2 = f"https://{self.maildomain_host}/v2/hme"
        self.session = session or requests.Session()
        self.session.headers.update(browser_headers(region, self.cookie))
        self.session.trust_env = False

    def _request_json(self, method: str, url: str, **kwargs) -> dict:
        last_error = ""
        for attempt in range(REQUEST_RETRIES):
            try:
                resp = self.session.request(method, url, timeout=REQUEST_TIMEOUT_SECONDS, **kwargs)
                try:
                    data = resp.json()
                except Exception:
                    data = _json_error(f"Unexpected response HTTP {resp.status_code}: {(resp.text or '')[:180]}")
                if resp.status_code >= 400 and not data.get("error"):
                    data["error"] = {"code": str(resp.status_code), "message": (resp.text or "")[:180]}
                return data
            except requests.Timeout:
                last_error = f"Request timed out after {REQUEST_TIMEOUT_SECONDS}s"
            except Exception as e:  # noqa: BLE001
                last_error = str(e)
            if attempt < REQUEST_RETRIES - 1:
                time.sleep(1)
        return _json_error(last_error or "Request failed")

    def validate_account(self) -> dict:
        data = self._request_json("GET", REGION_CONFIG[self.region]["setup_validate_url"])
        if data.get("error"):
            return data
        detected = data.get("detectedMaildomainHost") or self.maildomain_host
        inferred = maildomain_from_partition(self.region, data.get("userPartition"))
        if inferred:
            detected = inferred
        web_host = ((data.get("webservices") or {}).get("maildomainws") or {}).get("url") or ""
        if web_host:
            parsed = urllib.parse.urlparse(web_host if "://" in web_host else f"https://{web_host}")
            if parsed.netloc:
                detected = parsed.netloc
        data["detectedMaildomainHost"] = detected
        return data

    @staticmethod
    def account_summary(account: dict) -> dict:
        ds_info = account.get("dsInfo") or {}
        full_name = ds_info.get("fullName") or " ".join(
            part for part in [ds_info.get("firstName"), ds_info.get("lastName")] if part
        )
        user_partition = account.get("userPartition")
        try:
            user_partition = int(user_partition) if user_partition is not None else None
        except (TypeError, ValueError):
            user_partition = None
        return {
            "apple_id": ds_info.get("appleId") or "Unknown",
            "name": full_name or "Unknown",
            "dsid": str(ds_info.get("dsid")) if ds_info.get("dsid") is not None else None,
            "user_partition": user_partition,
            "maildomain_host": account.get("detectedMaildomainHost") or "",
            "hide_my_email_available": bool(ds_info.get("isHideMyEmailFeatureAvailable")),
        }

    def generate_email(self) -> dict:
        return self._request_json(
            "POST",
            f"{self.base_url_v1}/generate",
            params=CLIENT_PARAMS,
            json={"langCode": REGION_CONFIG[self.region]["lang_code"]},
        )

    def reserve_email(self, email: str, label: str, note: str) -> dict:
        return self._request_json(
            "POST",
            f"{self.base_url_v1}/reserve",
            params=CLIENT_PARAMS,
            json={"hme": email, "label": label, "note": note},
        )

    def list_email(self) -> dict:
        return self._request_json("GET", f"{self.base_url_v2}/list", params=CLIENT_PARAMS)

    def generate_reserved(self, label: str, note: str = DEFAULT_HME_NOTE) -> dict:
        gen = self.generate_email()
        if not gen.get("success"):
            return gen
        email = ((gen.get("result") or {}).get("hme") or "").strip().lower()
        if not email:
            return _json_error(f"iCloud generate response missing result.hme: {gen}")
        reserve = self.reserve_email(email, label, note)
        if not reserve.get("success"):
            return reserve
        return {
            "success": True,
            "result": {
                "hme": email,
                "label": label,
                "note": note,
                "reserve": reserve.get("result") or {},
            },
        }


def strip_html(value: str) -> str:
    value = re.sub(r"(?is)<(script|style).*?>.*?</\1>", " ", value or "")
    value = TAG_RE.sub(" ", value)
    return html.unescape(value)


def normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def get_message_body(message: EmailMessage) -> str:
    plain_parts: list[str] = []
    html_parts: list[str] = []
    if message.is_multipart():
        for part in message.walk():
            if part.get_content_disposition() == "attachment":
                continue
            try:
                content = part.get_content()
            except Exception:
                continue
            if not isinstance(content, str):
                continue
            if part.get_content_type() == "text/plain":
                plain_parts.append(content)
            elif part.get_content_type() == "text/html":
                html_parts.append(strip_html(content))
    else:
        try:
            content = message.get_content()
        except Exception:
            content = ""
        if isinstance(content, str):
            if message.get_content_type() == "text/html":
                html_parts.append(strip_html(content))
            else:
                plain_parts.append(content)
    body = "\n".join(p.strip() for p in plain_parts if p.strip())
    return body or "\n".join(p.strip() for p in html_parts if p.strip())


def extract_verification_code(subject: str, body: str) -> str:
    text = normalize_space(f"{subject}\n{body}")
    if not text:
        return ""
    candidates: list[tuple[int, str]] = []
    for regex, base_score in ((DIGIT_CODE_RE, 50), (ALNUM_CODE_RE, 20)):
        for match in regex.finditer(text.upper()):
            code = match.group(0)
            start, end = match.span()
            window = text[max(0, start - 80): min(len(text), end + 80)]
            if not CODE_KEYWORDS_RE.search(window):
                continue
            if re.fullmatch(r"(?:19|20)\d{2}", code):
                continue
            score = base_score + (20 if len(code) == 6 else 0) + (5 if len(code) in (4, 5, 7, 8) else 0)
            candidates.append((score, code))
    if not candidates:
        return ""
    candidates.sort(key=lambda item: item[0], reverse=True)
    return candidates[0][1]


def header_addresses(message: EmailMessage, names: Iterable[str]) -> list[str]:
    raw_values: list[str] = []
    for name in names:
        raw_values.extend(message.get_all(name, []))
    parsed = _email_utils.getaddresses(raw_values)
    return [addr.lower() for _, addr in parsed if addr]


def message_matches_target(message: EmailMessage, body: str, target_email: str) -> bool:
    target = (target_email or "").strip().lower()
    if not target:
        return False
    haystack = "\n".join([message.get(name, "") for name in RECIPIENT_HEADERS] + [body]).lower()
    if target in haystack:
        return True
    return target in header_addresses(message, RECIPIENT_HEADERS)


def encode_imap_folder(folder: str) -> str:
    """Encode mailbox name with IMAP modified UTF-7 when non-ASCII is present."""
    out: list[str] = []
    buf: list[str] = []

    def flush() -> None:
        if not buf:
            return
        raw = "".join(buf).encode("utf-16be")
        encoded = base64.b64encode(raw).decode("ascii").rstrip("=").replace("/", ",")
        out.append(f"&{encoded}-")
        buf.clear()

    for ch in folder:
        code = ord(ch)
        if 0x20 <= code <= 0x7E:
            flush()
            out.append("&-" if ch == "&" else ch)
        else:
            buf.append(ch)
    flush()
    return "".join(out)


def imap_folder_select_names(folder: str) -> list[str]:
    encoded = encode_imap_folder(folder)
    return [folder] if encoded == folder else [folder, encoded]


def parse_imap_folders(raw: str | Iterable[str] | None) -> list[str]:
    """Parse comma/newline/semicolon separated IMAP folders, preserving order."""
    if raw is None:
        parts: list[str] = []
    elif isinstance(raw, str):
        parts = re.split(r"[,;\r\n]+", raw)
    else:
        parts = [str(item) for item in raw]
    folders: list[str] = []
    seen: set[str] = set()
    for part in parts:
        folder = str(part or "").strip()
        if not folder:
            continue
        key = folder.casefold()
        if key in seen:
            continue
        seen.add(key)
        folders.append(folder)
    return folders or ["INBOX"]


def message_timestamp(message: EmailMessage) -> Optional[float]:
    """Best-effort RFC 5322 Date header timestamp for OTP freshness checks."""
    raw = message.get("Date", "")
    if not raw:
        return None
    try:
        parsed = _email_utils.parsedate_to_datetime(raw)
    except Exception:
        return None
    if parsed is None:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.timestamp()


@dataclass
class ICloudInboxConfig:
    host: str
    port: int
    username: str
    password: str
    folder: str = "INBOX"
    use_ssl: bool = True

    @property
    def folders(self) -> list[str]:
        return parse_imap_folders(self.folder)


class ICloudInboxPoller:
    def __init__(self, config: ICloudInboxConfig):
        self.config = config
        self._seen_uids: set[str] = set()

    def _connect(self):
        if self.config.use_ssl:
            return imaplib.IMAP4_SSL(self.config.host, self.config.port)
        return imaplib.IMAP4(self.config.host, self.config.port)

    def seed_seen(self, target_email: str, limit: int = 80, older_than: Optional[float] = None) -> None:
        try:
            for uid, _message in self._fetch_recent(limit=limit):
                if older_than is not None:
                    msg_ts = message_timestamp(_message)
                    if msg_ts is None or msg_ts >= older_than:
                        continue
                self._seen_uids.add(uid)
            logger.debug(f"[icloud_hme] 初始已有邮件 {len(self._seen_uids)} 封，跳过 target={target_email}")
        except Exception as e:  # noqa: BLE001
            logger.warning(f"[icloud_hme] 初始邮件列表拉取异常: {e}")

    def _fetch_recent(self, limit: int = 80):
        mailbox = self._connect()
        try:
            mailbox.login(self.config.username, self.config.password)
            for folder in self.config.folders:
                try:
                    selected_name = ""
                    status = "NO"
                    for select_name in imap_folder_select_names(folder):
                        try:
                            status, _ = mailbox.select(select_name, readonly=True)
                        except Exception as e:  # noqa: BLE001
                            logger.debug(f"[icloud_hme] IMAP folder={folder} select_name={select_name} 异常: {e}")
                            continue
                        if status == "OK":
                            selected_name = select_name
                            break
                    if status != "OK":
                        logger.warning(f"[icloud_hme] 跳过 IMAP folder={folder}: select failed")
                        continue
                    status, data = mailbox.uid("search", None, "ALL")
                    if status != "OK":
                        logger.warning(f"[icloud_hme] 跳过 IMAP folder={folder}: search failed")
                        continue
                    uids = data[0].split() if data and data[0] else []
                    if limit > 0:
                        uids = uids[-limit:]
                    for raw_uid in reversed(uids):
                        uid = raw_uid.decode("ascii", errors="ignore")
                        uid_key = f"{folder}::{uid}"
                        status, msg_data = mailbox.uid("fetch", raw_uid, "(RFC822)")
                        if status != "OK" or not msg_data:
                            continue
                        raw_message = b""
                        for part in msg_data:
                            if isinstance(part, tuple):
                                raw_message += part[1]
                        if raw_message:
                            yield uid_key, BytesParser(policy=policy.default).parsebytes(raw_message)
                except Exception as e:  # noqa: BLE001
                    logger.warning(f"[icloud_hme] IMAP folder={folder} 拉取异常: {e}")
                    continue
        finally:
            try:
                mailbox.logout()
            except Exception:
                pass

    def wait_for_otp(self, target_email: str, timeout: int = 120, issued_after: Optional[float] = None) -> str:
        timeout = max(int(timeout or 120), 60)
        deadline = time.time() + timeout
        freshness_threshold = (issued_after - 5) if issued_after else None
        logger.info(f"[icloud_hme] 等待 OTP -> {target_email} folders={self.config.folders} (timeout={timeout}s)")
        self.seed_seen(target_email, older_than=freshness_threshold)
        while time.time() < deadline:
            try:
                for uid, message in self._fetch_recent(limit=80):
                    if uid in self._seen_uids:
                        continue
                    self._seen_uids.add(uid)
                    msg_ts = message_timestamp(message)
                    if freshness_threshold is not None and msg_ts is not None and msg_ts < freshness_threshold:
                        logger.debug(f"[icloud_hme] uid={uid} 跳过: 早于发码时间")
                        continue
                    subject = str(message.get("Subject", ""))
                    body = get_message_body(message)
                    if not message_matches_target(message, body, target_email):
                        logger.debug(f"[icloud_hme] uid={uid} 跳过: 不匹配目标 HME")
                        continue
                    otp = extract_verification_code(subject, body)
                    if otp:
                        logger.info(f"[icloud_hme] ✅ OTP={otp} target={target_email} uid={uid}")
                        return otp
                    logger.debug(f"[icloud_hme] uid={uid} 未匹配到 OTP subject={subject[:80]}")
            except Exception as e:  # noqa: BLE001
                logger.warning(f"[icloud_hme] IMAP poll 异常 (重试): {e}")
            time.sleep(3)
        raise TimeoutError(f"iCloud HME OTP timeout {timeout}s for {target_email}")


class ICloudHMEMailProvider:
    """Provider interface compatible with AuthFlow.run_register."""

    def __init__(self, config: dict, db_module=None):
        self.config = config
        self.db = db_module
        self.current_email = ""
        self.claimed_email = ""
        self.requested_email = ""
        self.last_persona = None
        self._outlook_creds = None
        self.outlook_exhausted = False

    def _client(self) -> ICloudHMEClient:
        cookie = (self.config.get("icloud_cookie") or "").strip()
        if not cookie:
            raise RuntimeError("iCloud Cookie 未配置，请去「邮箱配置」Tab 填写")
        client = ICloudHMEClient(
            cookie=cookie,
            region=self.config.get("icloud_region") or "global",
            maildomain_host=self.config.get("icloud_maildomain_host") or "",
        )
        if not (self.config.get("icloud_maildomain_host") or "").strip():
            account = client.validate_account()
            if account.get("error"):
                err = account.get("error")
                msg = err.get("message") if isinstance(err, dict) else str(err)
                raise RuntimeError(f"iCloud Cookie 校验失败: {msg}")
            detected = account.get("detectedMaildomainHost") or client.maildomain_host
            if detected and detected != client.maildomain_host:
                client = ICloudHMEClient(
                    cookie=cookie,
                    region=self.config.get("icloud_region") or "global",
                    maildomain_host=detected,
                )
        return client

    def create_mailbox(self) -> str:
        if self.db is None:
            raise RuntimeError("iCloud provider 缺少 DB 模块")
        requested = (self.requested_email or "").strip().lower()
        row = self.db.claim_icloud_available(requested) if requested else self.db.claim_icloud_available()
        if row is None and requested:
            raise RuntimeError(f"iCloud HME 账号 {requested} 不可用（不存在 / 非 available / inactive）")
        if row is None and _truthy(self.config.get("icloud_auto_generate", True)):
            label_prefix = (self.config.get("icloud_label_prefix") or "gpt-register").strip() or "gpt-register"
            note = (self.config.get("icloud_note") or DEFAULT_HME_NOTE).strip() or DEFAULT_HME_NOTE
            label = f"{label_prefix}-{int(time.time())}"
            client = self._client()
            res = client.generate_reserved(label=label, note=note)
            if not res.get("success"):
                err = res.get("error") or res.get("reason") or res
                raise RuntimeError(f"iCloud HME 自动生成失败: {err}")
            result = res.get("result") or {}
            email = (result.get("hme") or "").lower()
            if not email:
                raise RuntimeError(f"iCloud HME 自动生成响应缺 hme: {res}")
            self.db.upsert_icloud_address({
                "email": email,
                "label": label,
                "note": note,
                "is_active": True,
                "state": "available",
                "source": "generated",
            })
            row = self.db.claim_icloud_available(email)
        if row is None:
            raise RuntimeError("iCloud HME 地址池没有 available 邮箱，且未启用自动生成")
        self.current_email = (row.get("email") or "").lower()
        self.claimed_email = self.current_email
        logger.info(f"[icloud_hme] 使用 HME 地址: {self.current_email}")
        return self.current_email

    def wait_for_otp(self, email_addr: str, timeout: int = 120, issued_after: Optional[float] = None) -> str:
        host = (self.config.get("icloud_imap_host") or "").strip()
        username = (self.config.get("icloud_imap_username") or "").strip()
        password = (self.config.get("icloud_imap_password") or "").strip()
        if not host or not username or not password:
            raise RuntimeError("iCloud HME IMAP 未配置完整（host / username / password）")
        cfg = ICloudInboxConfig(
            host=host,
            port=int(self.config.get("icloud_imap_port") or 993),
            username=username,
            password=password,
            folder=(self.config.get("icloud_imap_folder") or "INBOX").strip() or "INBOX",
            use_ssl=_truthy(self.config.get("icloud_imap_use_ssl", True)),
        )
        return ICloudInboxPoller(cfg).wait_for_otp(email_addr, timeout=timeout, issued_after=issued_after)


def validate_icloud_config(config: dict) -> dict:
    client = ICloudHMEClient(
        cookie=config.get("icloud_cookie") or "",
        region=config.get("icloud_region") or "global",
        maildomain_host=config.get("icloud_maildomain_host") or "",
    )
    account = client.validate_account()
    if account.get("error"):
        err = account.get("error")
        msg = err.get("message") if isinstance(err, dict) else str(err)
        raise RuntimeError(f"iCloud Cookie 校验失败: {msg}")
    summary = client.account_summary(account)

    imap_ok = False
    imap_message = "未配置 IMAP，跳过收件箱测试"
    host = (config.get("icloud_imap_host") or "").strip()
    username = (config.get("icloud_imap_username") or "").strip()
    password = (config.get("icloud_imap_password") or "").strip()
    if host and username and password:
        mailbox = None
        try:
            cfg = ICloudInboxConfig(
                host=host,
                port=int(config.get("icloud_imap_port") or 993),
                username=username,
                password=password,
                folder=(config.get("icloud_imap_folder") or "INBOX").strip() or "INBOX",
                use_ssl=_truthy(config.get("icloud_imap_use_ssl", True)),
            )
            mailbox = imaplib.IMAP4_SSL(cfg.host, cfg.port) if cfg.use_ssl else imaplib.IMAP4(cfg.host, cfg.port)
            mailbox.login(cfg.username, cfg.password)
            status, _ = mailbox.select(cfg.folder, readonly=True)
            if status != "OK":
                raise RuntimeError(f"无法选择 IMAP 文件夹: {cfg.folder}")
            imap_ok = True
            imap_message = "IMAP 连接成功"
        finally:
            if mailbox is not None:
                try:
                    mailbox.logout()
                except Exception:
                    pass
    return {"account": summary, "imap_ok": imap_ok, "imap_message": imap_message}
