<script setup>
import { onActivated, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getExportConfig, saveExportConfig, testExport } from '@/api/settings'
import FooterToolbar from '@/components/FooterToolbar.vue'

const cpa = reactive({ enabled: false, url: '', key: '', keyPh: 'Paste the CPA management key', timeout: 30 })
const sub = reactive({ enabled: false, url: '', key: '', keyPh: 'Paste the x-api-key generated by the dashboard', groupIds: '2', timeout: 30 })
const saving = ref(false)
const testingCpa = ref(false)
const testingSub = ref(false)

async function load() {
  try {
    const { config } = await getExportConfig()
    cpa.enabled = config.cpa_enabled === '1'
    cpa.url = config.cpa_url || ''
    cpa.key = ''
    cpa.keyPh = config.cpa_mgmt_key === '***' ? 'Already configured (leave blank to keep it)' : 'Paste the CPA management key'
    cpa.timeout = Number(config.cpa_timeout || 30)
    sub.enabled = config.sub2api_enabled === '1'
    sub.url = config.sub2api_url || ''
    sub.key = ''
    sub.keyPh = config.sub2api_api_key === '***' ? 'Already configured (leave blank to keep it)' : 'Paste the x-api-key generated by the dashboard'
    sub.groupIds = config.sub2api_group_ids || '2'
    sub.timeout = Number(config.sub2api_timeout || 30)
  } catch (e) { ElMessage.error(e.message) }
}

async function save() {
  saving.value = true
  try {
    await saveExportConfig({
      cpa_enabled: cpa.enabled ? '1' : '0',
      cpa_url: cpa.url.trim(),
      cpa_mgmt_key: cpa.key.trim() || '***',
      cpa_timeout: String(cpa.timeout || 30),
      sub2api_enabled: sub.enabled ? '1' : '0',
      sub2api_url: sub.url.trim(),
      sub2api_api_key: sub.key.trim() || '***',
      sub2api_group_ids: sub.groupIds.trim() || '2',
      sub2api_timeout: String(sub.timeout || 30),
    })
    ElMessage.success('Configuration saved')
    load()
  } catch (e) { ElMessage.error(e.message) }
  finally { saving.value = false }
}

async function test(target) {
  const flag = target === 'cpa' ? testingCpa : testingSub
  flag.value = true
  try { const r = await testExport(target); ElMessage.success(r.message || 'Connection successful') }
  catch (e) { ElMessage.error(e.message) }
  finally { flag.value = false }
}

onActivated(() => load())
</script>

<template>
  <div class="page">
    <el-card shadow="never" style="max-width: 760px">
      <template #header>
        <span class="section-title" style="margin: 0">Automatic Export After Registration</span>
        <el-tag type="danger" size="small" effect="dark" style="margin-left: 8px">Requires a refresh token</el-tag>
      </template>
      <p class="hint">When enabled, every successfully registered account is exported to the selected dashboard after it is saved. Disabled targets are never called. Export failures are logged and do not affect registration.</p>
      <p class="hint" style="color: var(--el-color-danger); font-weight: 600">
        Note: exported accounts require a <b>refresh token (RT)</b> to work. Configure an <b>SMS verification provider</b> to obtain refresh tokens.
      </p>

      <el-form label-position="top">
        <el-divider content-position="left">CPA Dashboard</el-divider>
        <el-form-item>
          <el-checkbox v-model="cpa.enabled">Enable automatic CPA export (POST /v0/management/auth-files)</el-checkbox>
        </el-form-item>
        <el-form-item label="CPA URL">
          <el-input v-model="cpa.url" placeholder="https://cpa.example.com" />
        </el-form-item>
        <el-form-item label="Management key (Authorization Bearer + X-Management-Key)">
          <el-input v-model="cpa.key" type="password" show-password :placeholder="cpa.keyPh" />
        </el-form-item>
        <el-form-item label="Timeout (seconds)">
          <el-input-number v-model="cpa.timeout" :min="5" :max="300" />
        </el-form-item>
        <el-button :loading="testingCpa" @click="test('cpa')">Test CPA Connection</el-button>

        <el-divider content-position="left">SUB2API Dashboard</el-divider>
        <el-form-item>
          <el-checkbox v-model="sub.enabled">Enable automatic SUB2API export (POST /api/v1/admin/accounts)</el-checkbox>
        </el-form-item>
        <el-form-item label="SUB2API URL">
          <el-input v-model="sub.url" placeholder="https://sub2api.example.com" />
        </el-form-item>
        <el-form-item label="API key (Security & Authentication → Administrator API Key)">
          <el-input v-model="sub.key" type="password" show-password :placeholder="sub.keyPh" />
        </el-form-item>
        <el-form-item label="Group IDs (comma-separated, e.g. 2 or 1,2,3)">
          <el-input v-model="sub.groupIds" placeholder="2" />
        </el-form-item>
        <el-form-item label="Timeout (seconds)">
          <el-input-number v-model="sub.timeout" :min="5" :max="300" />
        </el-form-item>
        <el-button :loading="testingSub" @click="test('sub2api')">Test SUB2API Connection</el-button>

      </el-form>
    </el-card>

    <FooterToolbar>
      <template #left>
        CPA {{ cpa.enabled ? 'enabled' : 'disabled' }} · SUB2API {{ sub.enabled ? 'enabled' : 'disabled' }}
      </template>
      <el-button type="primary" :loading="saving" @click="save">Save Configuration</el-button>
    </FooterToolbar>
  </div>
</template>
