<script setup>
import { computed, onActivated, ref } from 'vue'
import { ElMessage } from 'element-plus'
import {
  getMailConfig,
  saveMailConfig,
  testMail,
} from '@/api/settings'
import FooterToolbar from '@/components/FooterToolbar.vue'

const source = ref('outlook')
const cfApiUrl = ref('')
const cfDomain = ref('')
const cfAdminToken = ref('')
const tokenPlaceholder = ref('Worker 配置的 ADMIN_PASSWORDS')
const saving = ref(false)
const testing = ref(false)

const icloudRegion = ref('global')
const icloudCookie = ref('')
const icloudCookiePlaceholder = ref('粘贴 iCloud Cookie')
const icloudMaildomainHost = ref('')
const icloudLabelPrefix = ref('openai')
const icloudNote = ref('Generated by gpt-outlook-register')
const icloudAutoGenerate = ref(true)
const icloudImapHost = ref('')
const icloudImapPort = ref('993')
const icloudImapUsername = ref('')
const icloudImapPassword = ref('')
const icloudImapPasswordPlaceholder = ref('转发收件箱 IMAP 密码')
const icloudImapFolder = ref('INBOX, Junk')
const icloudImapUseSsl = ref(true)
const icloudTestResult = ref(null)

const sourceLabel = computed(() => {
  if (source.value === 'cf_temp') return 'CF Temp Email'
  if (source.value === 'icloud_hme') return 'iCloud Hide My Email'
  return 'Outlook 接码池'
})

function boolValue(v, fallback = false) {
  if (v === true || v === '1' || v === 1 || v === 'true') return true
  if (v === false || v === '0' || v === 0 || v === 'false') return false
  return fallback
}

function buildPayload() {
  return {
    mail_source: source.value,
    cf_api_url: source.value === 'cf_temp' ? cfApiUrl.value.trim() : '',
    cf_admin_token: source.value === 'cf_temp' ? (cfAdminToken.value.trim() || '***') : '***',
    cf_domain: source.value === 'cf_temp' ? cfDomain.value.trim() : '',
    icloud_region: icloudRegion.value || 'global',
    icloud_cookie: icloudCookie.value.trim() || '***',
    icloud_maildomain_host: icloudMaildomainHost.value.trim(),
    icloud_label_prefix: icloudLabelPrefix.value.trim(),
    icloud_note: icloudNote.value.trim(),
    icloud_auto_generate: icloudAutoGenerate.value ? '1' : '0',
    icloud_imap_host: icloudImapHost.value.trim(),
    icloud_imap_port: String(icloudImapPort.value || '').trim() || '993',
    icloud_imap_username: icloudImapUsername.value.trim(),
    icloud_imap_password: icloudImapPassword.value.trim() || '***',
    icloud_imap_folder: icloudImapFolder.value.trim() || 'INBOX',
    icloud_imap_use_ssl: icloudImapUseSsl.value ? '1' : '0',
  }
}

function testSummary(result) {
  if (!result) return ''
  const parts = []
  const accountObj = result.account || result.icloud || {}
  const account = accountObj.apple_id || accountObj.appleId || accountObj.summary ||
    result.apple_id || result.appleId || result.apple_id_summary
  const dsid = accountObj.dsid || result.dsid || result.ds_id
  const partition = accountObj.userPartition || accountObj.user_partition ||
    result.userPartition || result.user_partition
  const maildomain = accountObj.maildomain_host || accountObj.maildomainHost ||
    result.maildomain_host || result.maildomainHost
  const imap = result.imap_ok ?? result.imap
  if (account) parts.push(`account: ${account}`)
  if (dsid) parts.push(`dsid: ${dsid}`)
  if (partition) parts.push(`partition: ${partition}`)
  if (maildomain) parts.push(`maildomain: ${maildomain}`)
  if (imap !== undefined) {
    const imapText = typeof imap === 'object' ? (imap.ok ? 'ok' : (imap.error || JSON.stringify(imap))) : imap
    parts.push(`imap: ${imapText === true ? 'ok' : imapText}`)
  }
  return parts.length ? parts.join('；') : (result.message || '连通正常')
}

async function load() {
  try {
    const { config } = await getMailConfig()
    source.value = config.mail_source || 'outlook'
    cfApiUrl.value = config.cf_api_url || ''
    cfDomain.value = config.cf_domain || ''
    cfAdminToken.value = ''
    tokenPlaceholder.value = config.cf_admin_token === '***'
      ? '已设置（留空保留原值）' : 'Worker 配置的 ADMIN_PASSWORDS'

    icloudRegion.value = config.icloud_region || 'global'
    icloudCookie.value = ''
    icloudCookiePlaceholder.value = config.icloud_cookie === '***'
      ? '已设置（留空保留原值）' : '粘贴 iCloud Cookie'
    icloudMaildomainHost.value = config.icloud_maildomain_host || ''
    icloudLabelPrefix.value = config.icloud_label_prefix || 'openai'
    icloudNote.value = config.icloud_note || 'Generated by gpt-outlook-register'
    icloudAutoGenerate.value = boolValue(config.icloud_auto_generate, true)
    icloudImapHost.value = config.icloud_imap_host || ''
    icloudImapPort.value = String(config.icloud_imap_port || '993')
    icloudImapUsername.value = config.icloud_imap_username || ''
    icloudImapPassword.value = ''
    icloudImapPasswordPlaceholder.value = config.icloud_imap_password === '***'
      ? '已设置（留空保留原值）' : '转发收件箱 IMAP 密码'
    icloudImapFolder.value = config.icloud_imap_folder || 'INBOX, Junk'
    icloudImapUseSsl.value = boolValue(config.icloud_imap_use_ssl, true)
  } catch (e) { ElMessage.error(e.message) }
}

async function save() {
  saving.value = true
  try {
    await saveMailConfig(buildPayload())
    ElMessage.success('保存成功')
    load()
  } catch (e) { ElMessage.error(e.message) }
  finally { saving.value = false }
}

async function test() {
  testing.value = true
  try {
    const r = await testMail(buildPayload())
    icloudTestResult.value = source.value === 'icloud_hme' ? r : null
    ElMessage.success(r.message || '连通正常')
  } catch (e) { ElMessage.error(e.message) }
  finally { testing.value = false }
}


onActivated(() => load())
</script>

<template>
  <div class="page">
    <el-card shadow="never" style="max-width: 860px">
      <template #header><span class="section-title" style="margin: 0">邮箱来源配置</span></template>
      <p class="hint">
        OpenAI 注册需要邮箱收 OTP。可选 Outlook 接码池（从邮箱列表 claim）、
        自建 CF Worker catch-all 邮箱，或 iCloud Hide My Email 账号池。
      </p>
      <el-form label-position="top">
        <el-form-item label="邮箱来源">
          <el-radio-group v-model="source">
            <el-radio value="outlook">Outlook 接码池</el-radio>
            <el-radio value="cf_temp">CF Temp Email（自建 catch-all）</el-radio>
            <el-radio value="icloud_hme">iCloud Hide My Email</el-radio>
          </el-radio-group>
        </el-form-item>

        <template v-if="source === 'cf_temp'">
          <el-form-item label="API URL（Worker 部署地址）">
            <el-input v-model="cfApiUrl" placeholder="https://mail.example.com" />
          </el-form-item>
          <el-form-item label="Admin Token（Worker 环境变量 ADMIN_PASSWORDS）">
            <el-input v-model="cfAdminToken" type="password" show-password :placeholder="tokenPlaceholder" />
          </el-form-item>
          <el-form-item label="Catch-all 域名">
            <el-input v-model="cfDomain" placeholder="example.com" />
          </el-form-item>
          <el-alert
            type="warning" :closable="false" show-icon
            title="需在 Cloudflare Email Routing 配置 catch-all 转发到 Worker，否则收不到邮件。"
          />
        </template>

        <template v-if="source === 'icloud_hme'">
          <el-alert
            type="info" :closable="false" show-icon style="margin-bottom: 16px"
            title="MVP 使用手动粘贴 iCloud Cookie + 转发收件箱 IMAP。Cookie/IMAP 密码留空会提交 ***，由后端保留已保存密钥。"
          />

          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="Region">
                <el-select v-model="icloudRegion" style="width: 100%">
                  <el-option label="global（www.icloud.com）" value="global" />
                  <el-option label="china（www.icloud.com.cn）" value="china" />
                </el-select>
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="maildomain_host（可留空自动推导）">
                <el-input v-model="icloudMaildomainHost" placeholder="p68-maildomainws.icloud.com" />
              </el-form-item>
            </el-col>
          </el-row>

          <el-form-item label="iCloud Cookie">
            <el-input
              v-model="icloudCookie" type="textarea" :rows="4" class="mono"
              :placeholder="icloudCookiePlaceholder"
            />
          </el-form-item>

          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="Label 前缀">
                <el-input v-model="icloudLabelPrefix" placeholder="openai" />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="默认 Note">
                <el-input v-model="icloudNote" placeholder="Generated by gpt-outlook-register" />
              </el-form-item>
            </el-col>
          </el-row>

          <el-form-item>
            <el-checkbox v-model="icloudAutoGenerate">
              <b>无可用账号时自动生成</b>（注册流程 claim 不到 available 账号时由后端生成并保留）
            </el-checkbox>
          </el-form-item>

          <el-divider content-position="left">转发收件箱 IMAP</el-divider>
          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="IMAP Host">
                <el-input v-model="icloudImapHost" placeholder="imap.example.com" />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="IMAP Port">
                <el-input v-model="icloudImapPort" type="number" placeholder="993" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="IMAP Username">
                <el-input v-model="icloudImapUsername" placeholder="forward-inbox@example.com" />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="IMAP Password">
                <el-input
                  v-model="icloudImapPassword" type="password" show-password
                  :placeholder="icloudImapPasswordPlaceholder"
                />
              </el-form-item>
            </el-col>
          </el-row>
          <el-row :gutter="16">
            <el-col :span="12">
              <el-form-item label="IMAP Folders（多个用逗号或换行分隔）">
                <el-input
                  v-model="icloudImapFolder"
                  type="textarea"
                  :rows="2"
                  placeholder="INBOX, Junk, Spam, 垃圾邮件"
                />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="SSL">
                <el-switch v-model="icloudImapUseSsl" active-text="SSL" inactive-text="明文" />
              </el-form-item>
            </el-col>
          </el-row>

          <el-alert
            type="warning" :closable="false" show-icon style="margin-top: 4px; margin-bottom: 12px"
            title="多个 iCloud HME 账号会转发到同一个 IMAP 收件箱；取码会按目标 HME 收件人匹配，建议同时填写 INBOX 和垃圾箱目录。"
          />

          <el-alert
            v-if="icloudTestResult" type="success" :closable="true" show-icon style="margin-top: 4px"
            title="iCloud 测试结果" :description="testSummary(icloudTestResult)"
            @close="icloudTestResult = null"
          />
        </template>

      </el-form>
    </el-card>


    <FooterToolbar>
      <template #left>邮箱来源：{{ sourceLabel }}</template>
      <el-button v-if="source === 'cf_temp'" :loading="testing" @click="test">测试 CF 连通性</el-button>
      <el-button v-if="source === 'icloud_hme'" :loading="testing" @click="test">测试 iCloud</el-button>
      <el-button type="primary" :loading="saving" @click="save">保存配置</el-button>
    </FooterToolbar>
  </div>
</template>
